# Old automations. Move to config/automations when needed.
- id: 'low light sensor'
  alias: 'Low light'
  initial_state: False
  trigger:
    platform: numeric_state
    entity_id: sensor.light_lux_sensor_3_0
    below: 30
  condition:
  - condition: state
    entity_id: group.personen
    state: 'home'
  - condition: state
    entity_id: group.woonkamer_lampen
    state: 'off'
  - condition: time
    after: '17:00:00'
    before: '23:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.woonkamer_avond

- id: 'chromecast woonkamer playing'
  alias: "Chromecast woonkamer playing"
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: media_player.woonkamer
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.woonkamer_chromecast_lights
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.woonkamer_avond_tv

- id: 'chromecast woonkamer paused'
  alias: "Chromecast woonkamer paused/stopped"
  initial_state: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.woonkamer_chromecast_lights
    state: 'on'
  trigger:
    platform: state
    entity_id: media_player.woonkamer
    from: 'playing'
  action:
  - service: scene.turn_on
    entity_id: scene.woonkamer_avond
