homeassistant:
  name: Home
  latitude: !secret geo_lat
  longitude: !secret geo_long
  elevation: 4
  unit_system: metric
  time_zone: !secret geo_time_zone
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant

config:
configurator:
conversation:
default_config:
device_tracker:
  exclude: !secret device_tracker_excluded_hosts
  home_interval: 10
  hosts: !secret device_tracker_hosts
  platform: nmap_tracker
  track_new_devices: true
discovery:
frontend:
http:
  base_url: !secret http_base_url
#  #ssl_certificate: !secret http_ssl_certificate
#  #ssl_key: !secret http_ssl_key
ifttt:
  key: !secret ifttt_key
logbook: !include config/logbook.yaml
mobile_app:
recorder:
  purge_interval: 1
  purge_keep_days: 7
sun:
system_health:
tts:
- platform: google_translate
  language: 'nl'
  base_url: !secret base_url
updater:
upnp:
  port_mapping: false # This is done manually on the router.
wake_on_lan:
zeroconf:

### Includes
google_assistant: !include config/google_assistant.yaml
group: !include groups.yaml
history: !include history.yaml
hue: !include devices/hue.yaml
media_player: !include devices/media_players.yaml
#mqtt: !include mqtt.yaml
notify: !include config/notify.yaml
panel_iframe: !include panel_iframe.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
spotify: !include config/spotify.yaml
sensor: !include devices/sensors.yaml
weather: !include weather.yaml
webostv: !include devices/webostv.yaml
yeelight: !include devices/yeelight.yaml
zone: !include zones.yaml

