alias: Go to bed
sequence:
- alias: Dim lights
  service: scene.turn_on
  entity_id: scene.woonkamer_pre_go_to_bed
- delay:
    minutes: 5
- alias: Turn off lights completely
  service: light.turn_off
  data:
    entity_id: light.woonkamer
    transition: 10
