- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: ipv4_address
      arg: wlan0

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
  - 0
  hourly_forecast:
  - 0
  - 1
  language: nl
  monitored_conditions:
  - summary
  - icon
  - precip_type
  - precip_intensity
  - precip_accumulation
  - temperature
  - wind_speed
  - hourly_summary
  - temperature_low
  - temperature_high
  - sunrise_time
  - sunset_time

- platform: cert_expiry
  host: !secret home_assistant_url
  name: Certificate Expiration
  port: !secret home_assistant_port
