- platform: time_date
  display_options:
    - 'date_time'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: ipv4_address
      arg: wlan0
    - type: since_last_boot

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
  - summary
  - icon
  - precip_type
  - temperature
  - wind_speed
  - temperature_min
  - temperature_max

- platform: cert_expiry
  host: !secret home_assistant_url
  name: Certificate Expiration
  port: !secret home_assistant_port
