project_id: !secret google_assistant_project_id
service_account: !include SERVICE_ACCOUNT.JSON
report_state: true
expose_by_default: false
entity_config:
  media_player.lg_woonkamer:
    name: LG Woonkamer
    aliases: 
    - TV_IN_DE_WOONKAMER
    room: woonkamer

